symbol: "QQQ"
bars_csv: "data/equities/QQQ_RTH_NH.csv"
feature_spec: "python/feature_spec.json"

out_dir: "artifacts/TFA/v1"
batch_size: 8192
epochs: 10
lr: 0.001
num_workers: 6
prefetch_factor: 4
hidden: 128

label_horizon: 1
label_kind: "logret_fwd"
